### ISSUE TITLE
Response limit.

### ISSUE THREAD

**Issue by Thesyjaga** [ImNotOssy/BBAE_investing_API#6]
So what I mean is that make sure to have a certain limit on the response you can send to the app for example you could look at fennel invest by Nelson Dane people got waring for using api because the fennel api did too much response to the servers

**Comment by ImNotOssy** [comment]
> So what I mean is that make sure to have a certain limit on the response you can send to the app for example you could look at fennel invest by Nelson Dane people got waring for using api because the fennel api did too much response to the servers

Hey, thank you so much for the suggestion, I will talk over with nelson to see what i can do.
