### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by Codin1223** [ImNotOssy/BBAE_investing_API#7]
Hi, I am really unaware how to use this code because I am using public lib from nelsondane and it has instructions in order to login and place orders. How do i even login and buy or sell?

could you give me example or possibly a guide like this

![image](https://github.com/user-attachments/assets/ad8ccf0d-4c01-4f91-a7d4-32ea311d7920)

**Comment by ImNotOssy** [comment]
> Hi, I am really unaware how to use this code because I am using public lib from nelsondane and it has instructions in order to login and place orders. How do i even login and buy or sell?
> 
> could you give me example or possibly a guide like this
> 
> ![image](https://github.com/user-attachments/assets/ad8ccf0d-4c01-4f91-a7d4-32ea311d7920)
> 
> 

This code is already implemented inside the autoRSA. If you're using that, you can use this.

**Comment by Codin1223** [comment]
I am just trying to buy and sell orders casual

**Comment by Codin1223** [comment]
is there commands for that? or do i need to do any workarounds?

**Comment by Codin1223** [comment]
nvm i coded myself
